### PR TITLE
[RFC] AsyncIO rewrite

### PR DESCRIPTION
**Pull request by felixonmars**
This is the ongoing effort to rewrite nvchecker with asyncio, aiohttp and pytest-asyncio

### CODE REVIEW

**Comment by lilydjwg** [comment]
We need to put all requests inside one `ClientSession` to gain conneciton reuse.

**Comment by lilydjwg** [comment]
Does this mean that, we can support proxies for all sources making HTTP requests?

**Comment by felixonmars** [comment]
@lilydjwg Yes I think.

**Comment by lilydjwg** [comment]
We need to test proxy settings now....

**Pull request merged**
