### PR TITLE
Also test tornado<5

### PR DESCRIPTION
**Pull request by yan12125**
I'm just too lazy to test it locally before creating a pull request :P

### CODE REVIEW

**Comment by yan12125** [comment]
Not sure why Python 3.5 is going crazy here. I can't reproduce the error locally with python35, and in [a previous run](https://travis-ci.org/lilydjwg/nvchecker/builds/406815302), 3.5 works fine with tornado.

**Comment by lilydjwg** [comment]
AUR returns None === networking issues.

**Comment by lilydjwg** [comment]
Shouldn't you update setup.py too?

**Comment by yan12125** [comment]
> Shouldn't you update setup.py too?

Done! Unfortunately networking on Travis CI VMs are too unstable :/

**Pull request merged**
