### PR TITLE
Add CRAN support

### PR DESCRIPTION
**Pull request by pekkarr**
Add CRAN support using per-package [DESCRIPTION](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) files unlike the previous pr (#184) that downloaded the entire database.

### CODE REVIEW

**Comment by lilydjwg** [comment]
Thanks!

**Comment by lilydjwg** [comment]
cc @hubutui

**Comment by hubutui** [comment]
great work!

**Comment by pekkarr** [comment]
Thank you!

**Pull request merged**
