### PR TITLE
support no_proxy and proxy from environment variables

### PR DESCRIPTION
**Pull request by juliantaylor**
support the no_proxy configuration option and also allow setting the
variable from the environment via:
http_proxy/HTTP_PROXY, no_proxy/NO_PROXY

fixes gh-101

### CODE REVIEW

**Comment by juliantaylor** [comment]
I haven't added documentation yet, I can do so if this change is ok for you

**Comment by lilydjwg** [comment]
1. `HTTP_PROXY` is commonly not used due to PHP and ancient code;
2. `HTTPS_PROXY` or `https_proxy` should be used for `https://` urls
3. We'd better let the HTTP library in use to pick up these, so they can support whatever they support (e.g. socks5h for curl)

**Comment by juliantaylor** [comment]
some tools also use HTTP_PROXY but I can restrict it to the lower case variants if you like

in the issues linked in the code none of the used libraries support using environment variables
tornado hardcodes pycurl to not use them and aiohttp does not support no_proxy (a mr exists but it is stalled since a year)

supporting https_proxy could make sense, I'll see if I can add it too

**Comment by juliantaylor** [comment]
removed uppercase variables and added https_proxy

note that curl documents these variables except http_proxy as uppercase

**Comment by juliantaylor** [comment]
anything else you still want changed?

**Comment by lilydjwg** [comment]
On Sat, Jul 18, 2020 at 04:43:17AM -0700, Julian Taylor wrote:
> anything else you still want changed?

No. I did't have time to review, sorry.

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
Here's my plan:

* request tornado to not explicitly set no proxy; curl has wide proxy support and is very reliable
* pass `trust_env=True` for aiohttp: if aiohttp doesn't support `no_proxy`, then we don't support if aiohttp is going to be used. Proxy support varies across HTTP clients
* nothing need to be done for httpx: httpx supports HTTP(S) proxy via environment variables including `no_proxy` by default.

**Comment by lilydjwg** [comment]
Pull request to pycurl: https://github.com/pycurl/pycurl/pull/640.
Commit for tornado: https://github.com/lilydjwg/tornado/commit/bbf4ecdca9d1290ed478575c15539a4a064cafd9

**Comment by juliantaylor** [comment]
Great! fixing the libraries is the best option, I didn't dig as deep down to see why pycurl does not allow unsetting it. Good that it can be done now.

It will take a while until both packages have updated and released but I can probably live with a fork until then.

**Comment by lilydjwg** [comment]
Both pycurl (https://github.com/pycurl/pycurl/pull/640) and tornado (https://github.com/tornadoweb/tornado/pull/2902) have merged the necessary changes, closing.

**Pull request closed without merging**
