### PR TITLE
Add OpenVSX and Visual Studio Code Marketplace sources

### PR DESCRIPTION
**Pull request by Th3Whit3Wolf**

### CODE REVIEW

**Comment by Th3Whit3Wolf** [comment]
I accidentally renamed `get_version` in the test. Fixed now.

**Comment by lilydjwg** [comment]
The code seems fine. Could you update the doc (at docs/usage.rst) too?

**Comment by Th3Whit3Wolf** [comment]
It's updated.

**Comment by Th3Whit3Wolf** [comment]
[This good?](https://github.com/lilydjwg/nvchecker/pull/195/files#diff-c4b284a0e8c330264ebefb4d3d14dd5bb68fe3b72c2ae656f49132e2c134b84f)

**Comment by lilydjwg** [comment]
Oh yes. I missed that.

**Comment by lilydjwg** [comment]
It's merged with a little rebase. GitHub seems to not detect that.

**Pull request closed without merging**
