### PR TITLE
Fix 403 errors from crates.io

### PR DESCRIPTION
**Pull request by yan12125**

### CODE REVIEW

**Comment by yan12125** [comment]
As a side note, from https://tools.ietf.org/html/rfc7231:

> A user agent SHOULD send a User-Agent field in each request unless specifically configured not to do so.

**Comment by lilydjwg** [comment]
On Thu, Jul 04, 2019 at 07:29:58AM -0700, Chih-Hsuan Yen wrote:
> As a side note, from https://tools.ietf.org/html/rfc7231:
> 
> > A user agent SHOULD send a User-Agent field in each request unless specifically configured not to do so.

This can be forwarded to tornado.

-- 
Best regards,
lilydjwg

**Comment by yan12125** [comment]
> This can be forwarded to tornado.

I agree.

**Comment by yan12125** [comment]
AUR tests are still as flaky as usual :/

**Comment by lilydjwg** [comment]
I'd like to set the user agent in session so we don't need to set it per request. Also, the version can be added to the user agent string.

**Comment by yan12125** [comment]
> I'd like to set the user agent in session so we don't need to set it per request. Also, the version can be added to the user agent string.

I'll check it out later.

By the way, do you think it's a good idea to elevate regex's `user_agent` to a gloabl option?

**Comment by lilydjwg** [comment]
A global `user_agent` is good but should be separate from the regex one. The regex one is to cope with sites that behave poorly with unexpected user agents (e.g. bilibili).

**Comment by yan12125** [comment]
Turns out global `user_agent` needs quite a few changes. I give up the idea this time.

**Comment by lilydjwg** [comment]
pytest-httpbin doesn't work with nightly. Also it brings in too many dependencies. I'll remove it.

**Comment by yan12125** [comment]
Well, I still think it's better not to test against the actual httpbin.org site.

By the way, the Python 3.8 issue is already fixed in git-master of werkzeug: https://github.com/pallets/werkzeug/issues/1551.

**Pull request merged**
