### PR TITLE
Add all option to cmp

### PR DESCRIPTION
**Pull request by trathborne**
It's also useful to be able to report packages without a changed version!

Now displaying both versions in green with == instead of an arrow.

### CODE REVIEW

**Comment by lilydjwg** [comment]
There is a conflict here now. Could you resolve it?

**Comment by trathborne** [comment]
Hmm, and maybe the part at the end which picks the arrow symbol and the color could be a dictionary lookup?

**Comment by lilydjwg** [comment]
The updated code doesn't look right. It always shows all versions and with a `==` symbol.

**Comment by lilydjwg** [comment]
> which picks the arrow symbol and the color could be a dictionary lookup?

Yes, it'll look better.

**Comment by trathborne** [comment]
Haha it's a typo, `if` in the middle of the `if..elif..elif..if..elif` ... dictionary version coming right up!

**Comment by trathborne** [comment]
Dammit still buggy

**Comment by trathborne** [comment]
Ok _now_ I think that's right. My mistake for coding before coffee!

**Comment by trathborne** [comment]
mypy is being pedantic. We know that the diff is going to have a 'delta'. Should that be `diffstyles[diff.get('delta', 'equal')]` to make mypy shut up?

**Comment by trathborne** [comment]
Any idea what will make mypy happy?

**Pull request merged**
