### PR TITLE
android-sdk improvements

### PR DESCRIPTION
**Pull request by yan12125**
* Returns all matched versions to support list options
* Don't hard-code the host OS
* Document the default of `channel`

---

I'm lazy so I put different changes in a single commit. Please tell me if you want separate commits :D

### CODE REVIEW

**Comment by yan12125** [comment]
Oh, after a long unmaintained period, httpbin is now completely broken... https://github.com/postmanlabs/httpbin/issues/673

I will try pin an older werkzeug like others do as a temporary workaround.

**Comment by lilydjwg** [comment]
Oops, latest werkzeug breaks quite a lot of things. I'll wait for your fix to the tests.

**Comment by yan12125** [comment]
Oh, you're as fast as thunder :) I'm still looking at mypy errors.

**Comment by lilydjwg** [comment]
I have caught up with lilac, yay!

**Comment by yan12125** [comment]
> Oh, after a long unmaintained period, httpbin is now completely broken...

Hit by this again today when I tried to upgrade community/nvchecker package in Arch Linux. I proposed to backport the fix in Arch https://bugs.archlinux.org/task/74443. Let's see how Felix thinks.

**Pull request merged**
