### PR TITLE
Pacman fixes and updates

### PR DESCRIPTION
**Pull request by yan12125**
Both are quite straightforward. See commit meesages for details.

### CODE REVIEW

**Comment by lilydjwg** [comment]
wtf this bug was there for so long....

**Comment by yan12125** [comment]
Do you mean the missing `| head -n 1`? Maybe just because nobody is running tests with [*testing] enabled.

**Comment by lilydjwg** [comment]
I mean the cache key.

**Comment by yan12125** [comment]
Oh yeah. Cache might should have been tested. I'll find time to try the approach for testing cache mentioned in https://github.com/lilydjwg/nvchecker/pull/62#issuecomment-341916567 again.

**Comment by lilydjwg** [comment]
There is a test for caching but it's too simple to make the issue happen.

**Comment by yan12125** [comment]
Oops, didn't notice test_cache. Yep it can be extended.

**Pull request merged**
