### PR TITLE
Bitbucket: Add support for queries and sorting

### PR DESCRIPTION
**Pull request by alexfikl**
Make better use of the bitbucket API to sort tags:

* use `q="my_query"` to narrow down the results. This does not support fancy regex queries, just `contains` and comparisons.
* use `sort=field` to sort the results by the given field.
* use `fields=values.name,next` to only return relevant data.

### CODE REVIEW

**Comment by lilydjwg** [comment]
I didn't know bitbucket has query and sort support on this. I'd like to utilize this instead of paging, like [the github source does](https://github.com/lilydjwg/nvchecker/blob/2f61336ce3bbe741f4278787a75689e3786056e2/nvchecker_source/github.py#L45).

**Comment by alexfikl** [comment]
> I didn't know bitbucket has query and sort support on this. I'd like to utilize this instead of paging, like [the github source does](https://github.com/lilydjwg/nvchecker/blob/2f61336ce3bbe741f4278787a75689e3786056e2/nvchecker_source/github.py#L45).

Not super familiar with the bitbucket API, but it seems like the results are always paginated, even when sorted or filtered. 

I can definitely use the sorted results to get a latest tag like the github plugin. Is that what you meant?

**Comment by lilydjwg** [comment]
I want to expose the `q` and `sort` parameters from the API to the configuration, and we only return results on the first page. Hopefully the desired tag can be `q`ueried and `sort`ed to be on the first page, and any outliners can be filtered using the "list options" mechanism.

We may add three new options: `use_sorted_tags` (not `latest` since we can sort differently) means to use this new behavior and optional `query` and `sort` can be provided, and we pass those directly to bitbucket's API.

(However the old behavior needs to be kept for backward compatibility.)

**Comment by alexfikl** [comment]
> I want to expose the `q` and `sort` parameters from the API to the configuration, and we only return results on the first page. Hopefully the desired tag can be `q`ueried and `sort`ed to be on the first page, and any outliners can be filtered using the "list options" mechanism.
> 
> We may add three new options: `use_sorted_tags` (not `latest` since we can sort differently) means to use this new behavior and optional `query` and `sort` can be provided, and we pass those directly to bitbucket's API.
> 
> (However the old behavior needs to be kept for backward compatibility.)

Tried do implement something like that in a8228bb. It seems to work for the simple tests I played with. What do you think?

**Comment by alexfikl** [comment]
There are a few other things we can add to the query:
* `fields=values.name` tells bitbucket to only return the tag names (as that's all we use anyway). This could be always added?
* `pagelen=NUMBER` can return more results (default is just 10). This could be a config option like `max_page`?

**Comment by lilydjwg** [comment]
* Yes, the smaller the response is, the faster it works.
* I don't feel like we need to add `pagelen`. `max_page` is for repos with a lot of unwanted tags, but since we can sort and filter, it should be unlikely we need a large `pagelen` to get what we want. Users can open an issue if it's actually useful.

**Comment by alexfikl** [comment]
> * Yes, the smaller the response is, the faster it works.

Added support for this in the latest commit and fixed the mypy issues (at least locally, fingers crossed!).

**Pull request merged**
